### ISSUE TITLE
test_sparse_weights_1d and test_sparse_weights_2d tests not passing

### ISSUE THREAD

**Issue by MohanadOdema** [numenta/nupic.torch#55]
Hi,

I installed the nupic.torch framework using _python setup.py develop_ as in the readme file. However, when I reach the test phase, all tests are successfully completed except test_sparse_weights_1d and test_sparse_weights_2d. I'm working on windows 10 with python 3.7.6 and pytorch 1.3. 

The error Traceback is as follows:

ERROR: test_sparse_weights_1d (tests.sparse_weights_test.TestSparseWeights)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\lenovo\documents\github\nupic.torch\tests\sparse_weights_test.py", line 36, in test_sparse_weights_1d
    sparse = SparseWeights(linear, percent_on)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 120, in __init__
    super(SparseWeights, self).__init__(module, weight_sparsity)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 78, in __init__
    self.rezero_weights()
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 143, in rezero_weights
    self.module.weight.data[zero_idx] = 0.0
IndexError: tensors used as indices must be long, byte or bool tensors

======================================================================
ERROR: test_sparse_weights_2d (tests.sparse_weights_test.TestSparseWeights)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\lenovo\documents\github\nupic.torch\tests\sparse_weights_test.py", line 53, in test_sparse_weights_2d
    sparse = SparseWeights2d(cnn, percent_on)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 159, in __init__
    super(SparseWeights2d, self).__init__(module, weight_sparsity)
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 78, in __init__
    self.rezero_weights()
  File "C:\Users\Lenovo\Documents\GitHub\nupic.torch\nupic\torch\modules\sparse_weights.py", line 187, in rezero_weights
    self.module.weight.data.view(self.module.out_channels, -1)[zero_idx] = 0.0
IndexError: tensors used as indices must be long, byte or bool tensors

----------------------------------------------------------------------
Ran 21 tests in 0.109s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=21 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=21 errors=2 failures=0>

**Comment by ayaz-amin** [comment]
Hi there! I just managed to find out what was wrong with the code (and I fixed it, can say it works for me at least). The problem comes from the ```sparse_weights.py``` file because indexing is being performed using int32 tensors. To fix this, uninstall nupic.torch, download the source and go to:
```sparse_weights.py```
Then update these lines:
line 142:
```python
zero_idx = (self.zero_weights[0], self.zero_weights[1])
```
to 
```
zero_idx = (self.zero_weights[0].long(), self.zero_weights[1].long())
```

and line 186:
```python
zero_idx = (self.zero_weights[0], self.zero_weights[1])
```
to 
```
zero_idx = (self.zero_weights[0].long(), self.zero_weights[1].long())
```

Hope this helps!
