### ISSUE TITLE
setup  is a fail

### ISSUE THREAD

**Issue by TZLhenshuai** [numenta/nupic.torch#78]
(nupic) beta@mole:~/disk/tzl/code/nupic.torch-master$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    tests_require=["pytest>=4.4.0"],
  File "/home/beta/anaconda3/envs/nupic/lib/python3.7/site-packages/setuptools/__init__.py", line 162, in setup
    _install_setup_requires(attrs)
  File "/home/beta/anaconda3/envs/nupic/lib/python3.7/site-packages/setuptools/__init__.py", line 157, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/beta/anaconda3/envs/nupic/lib/python3.7/site-packages/setuptools/dist.py", line 702, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/beta/anaconda3/envs/nupic/lib/python3.7/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pycodestyle 2.6.0 (/home/beta/disk/tzl/code/nupic.torch-master/.eggs/pycodestyle-2.6.0-py3.7.egg), Requirement.parse('pycodestyle<2.6.0,>=2.5.0'), {'flake8'})

**Comment by FeStein** [comment]
I recently got nearly the same error with the exception, that I'm using python 3.8. You're missing the [pycodstyle](https://pypi.org/project/pycodestyle/) package. You can manually install it via pip:  
`pip3 install pycodestyle`  
after that run
`python3 setup.py develop`
and the installation should work. The package should most likely be added to the requirements.
